spring.datasource.url=jdbc:mariadb://localhost:3306/customer_management?rewriteBatchedStatements=true
spring.datasource.username=springuser
spring.datasource.password=springpass
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.generate_statistics=false
spring.cache.type=simple

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
spring.servlet.multipart.resolve-lazily=true

server.tomcat.max-http-form-post-size=200MB
server.tomcat.connection-timeout=600000

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5

server.port=8080